# Spring
spring:
  data:
    mongodb:
      username: admin
      password: BestPass
      database: courseDB
      host: 127.0.0.1
      port: 27017
  application:
    name: courses
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master

# Server
server:
  port: 8082
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# JMA properties
jma:
  service:
    user: USERS

# Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
