# Spring
spring:
  data:
    mongodb:
      username: admin
      password: BestPass
      database: courseDB
      host: 127.0.0.1
      port: 27017
  application:
    name: courses

# Server
server:
  port: 8082
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/